### ISSUE TITLE
Fix en_indexer

### ISSUE THREAD

**Issue by jag3773** [Door43/tools#40]
This line https://github.com/Door43/tools/blob/master/general_tools/en_indexer.sh#L10 needs fixed to hit the correct URL to trigger an index of the page.

**Comment by superdav42** [comment]
@jag3773 made [PR](https://github.com/Door43/tools/issues/41) for this. Not sure what our practice is here but I'm used to making all code changes to master with pull requests so they can be peer reviewed.

**Comment by jag3773** [comment]
Perfect. Thanks!
